---
title: "TidyTemplate"
date: 2021-05-19
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(broom)
library(lubridate)

theme_set(theme_light())

```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2021-05-18")

```


# Readme

```{r Readme, eval = interactive()}

tt

```

```{r Load}

survey <- tt$survey %>%
  mutate(timestamp = mdy_hms(timestamp),
         age_category = fct_relevel(fct_reorder(how_old_are_you, parse_number(how_old_are_you)), "under 18"),
         experience_overall = str_replace(overall_years_of_professional_experience, " - ", "-"),
         experience_overall = fct_reorder(experience_overall, parse_number(experience_overall)),
         experience_in_field = str_replace(years_of_experience_in_field, " - ", "-"),
         experience_in_field = fct_reorder(experience_in_field, parse_number(experience_in_field))) %>%
  mutate(gender = fct_collapse(coalesce(gender, "Other or prefer not to answer"), "Other or prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer")),
         race = fct_lump(coalesce(race, "Other"), 4))

survey %>%
  count(years_of_experience_in_field)

survey %>%
  count(industry, sort = TRUE)

survey %>%
  count(job_title, sort = TRUE)

survey %>%
  count(currency, sort = TRUE)
```

```{r}

survey_usd <- survey %>%
  filter(currency == "USD") %>%
  filter(annual_salary >= 5000,
         annual_salary <= 2e6) %>%
  mutate(state = str_remove(state, ", .*"))

```

```{r}

survey_usd %>%
  ggplot(aes(annual_salary)) +
  geom_histogram() +
  scale_x_log10(labels = dollar_format()) +
  labs(x = "Annual")

summarize_salary <- function(tbl) {
  tbl %>%
    summarize(n = n(),
              median_salary = median(annual_salary)) %>%
    arrange(desc(n))
}

plot_categorical <- function(tbl, column, n_levels = 9, reorder = TRUE) {
  
  lumped_tbl <- tbl %>%
    filter(!is.na({{ column }})) %>%
    mutate({{ column }} := fct_lump({{ column }}, n_levels))
  
  if (reorder) {
    lumped_tbl <- lumped_tbl %>%
      mutate({{ column }} := fct_reorder({{ column }}, annual_salary))
  }
  
  lumped_tbl %>%
    group_by({{ column }}) %>%
    summarize_salary() %>%
    ggplot(aes(median_salary, {{ column }})) +
    geom_col() +
    scale_x_continuous(labels = dollar_format()) +
    labs(x = "Median salary")
}

survey_usd %>%
  plot_categorical(state)

survey_usd %>%
  plot_categorical(industry)

survey_usd %>%
  plot_categorical(job_title, n_levels = 10)

survey_usd %>%
  plot_categorical(experience_overall, reorder = FALSE)

survey_usd %>%
  plot_categorical(experience_in_field, reorder = FALSE)

survey_usd %>%
  plot_categorical(age_category, reorder = FALSE)

survey_usd %>%
  plot_categorical(gender)

survey_usd %>%
  plot_categorical(race, n_levels = 4)
```



### ANOVA

```{r}
survey_usd %>%
  filter(!is.na(experience_overall)) %>%
  ggplot(aes(annual_salary, experience_overall)) +
  geom_boxplot() +
  scale_x_log10()

lm(log2(annual_salary) ~ experience_overall, data = survey_usd)

lm(log2(annual_salary) ~ experience_in_field, data = survey_usd) %>%
  summary()

survey_usd %>%
  mutate(job_title = fct_lump(job_title, 20)) %>%
  lm(log2(annual_salary) ~ job_title, data = .) %>%
  summary()

survey_usd %>%
  mutate(job_title = fct_lump(job_title, 10),
         state = fct_lump(state, 10),
         industry = fct_lump(industry, 10)) %>%
  lm(log2(annual_salary) ~ job_title + state + experience_in_field + gender + race + industry, data = .) %>%
  anova() %>%
  tidy() %>%
  mutate(pct_variation = sumsq / sum(sumsq)) %>%
  arrange(desc(pct_variation))

```


## Machine Learning




























