---
title: "World Freedom Index"
date: 2022-09-18
output: html_document
editor_options: 
  chunk_output_type: console
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(janitor)
library(WDI)
library(countrycode)
library(broom)
library(ggrepel)
library(fuzzyjoin)
library(gganimate)

theme_set(theme_light())

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2022-02-22")

```


# Readme


```{r Readme, eval = interactive()}

freedom <- tt$freedom %>% 
  clean_names() %>% 
  rename(civil_liberties = cl, political_rights = pr) %>% 
   mutate(country_code = countrycode(country, "country.name", "iso2c"))

```

```{r}

freedom %>% 
  count(year, sort = T) %>% 
  arrange(desc(year))

freedom %>% 
  distinct(country, region_name)

```

```{r}

summarize_freedom <- function(tbl) {
  tbl %>% 
    summarize(n_countries = n(),
            avg_civil_liberties = mean(civil_liberties),
            avg_political_rights = mean(political_rights),
            pct_free = mean(status == "F"),
              .groups = "drop") %>% 
    arrange(desc(n_countries))
}

freedom %>% 
  filter(year == 2020) %>% 
  arrange(desc(civil_liberties))

by_region <- freedom %>% 
  filter(year == 2020) %>% 
  group_by(region_name) %>% 
  summarize_freedom()
  

by_region %>% 
  ggplot(aes(avg_civil_liberties, avg_political_rights)) +
  geom_point(aes(size = n_countries)) +
  geom_abline(color = "red") +
  geom_text(aes(label = region_name), vjust = 1, hjust = 1) +
  expand_limits(x = 0, y = 0, size = 0)

```


```{r}

freedom %>% 
  ggplot(aes(civil_liberties)) +
  geom_histogram()

freedom %>% 
  filter(country == "United States of America") %>% 
  ggplot(aes(year, civil_liberties)) +
  geom_line()

freedom %>% 
  filter(year == 2020) %>% 
  ggplot(aes(civil_liberties, political_rights)) +
  geom_point() +
  geom_abline(color = "red") +
  geom_jitter(height = .2, width = .2) +
  expand_limits(x = 0, y = 0)

```


```{r}

freedom %>% 
  filter(year == 2020) %>% 
  arrange(desc(political_rights))

freedom %>% 
  summarize(sd(civil_liberties), sd(political_rights))

freedom %>% 
  filter(year == 2020) %>% 
  pivot_longer(c(civil_liberties, political_rights), names_to = "metric", values_to = "value") %>% 
  mutate(region_name = fct_reorder(region_name, value),
         metric = str_replace_all(metric, "_", " ") %>% str_to_title()) %>% 
  count(region_name, metric, value) %>% 
  ggplot(aes(value, n)) +
  geom_col() +
  facet_grid(region_name ~ metric) +
  labs(x = "World Freedom Index rating", y = "# of countries",
       title = "Distribution of World Fredom Index by region in 2020")

```


```{r}

freedom_gathered <- freedom %>% 
  pivot_longer(c(civil_liberties, political_rights), names_to = "metric", values_to = "value") %>% 
  mutate(
    metric = str_replace_all(metric, "_", " ") %>% str_to_title(),
    region_name = fct_reorder(region_name, value)
    ) 

overall <- freedom_gathered %>% 
  group_by(year, metric) %>% 
  summarize(avg_rating = mean(value))

freedom_gathered %>% 
  group_by(year,region_name, metric) %>% 
  summarize(avg_rating = mean(value)) %>% 
  ggplot(aes(year, avg_rating)) +
  geom_line(aes(color = region_name)) +
  geom_line(data = overall, size = 1.5) +
  facet_wrap(~ metric) +
  expand_limits(y = 1) +
  scale_y_reverse(breaks = seq(1, 7)) +
  scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  labs(x = "Year", y = "World Freedom Index rating",
       title = "World Freedom Index rating over time by region",
       color = "Region",
       subtitle = "Black line shows overall trend")

```

## World Bank Data

```{r}


gdp_percap <- WDI(indicator = "NY.GDP.PCAP.CD", 
                  extra = TRUE, 
                  start = 1995, 
                  end = 2020) %>% 
  as_tibble()

freedom_joined <- freedom_gathered %>% 
  inner_join(gdp_percap, by = c(country_code = "iso2c", "year"),
             suffix = c("", "_wdi")) %>% 
  mutate(
    income = fct_relevel(income, c("Low income", "Lower middle income", "Upper middle income", "High income")))

freedom_joined %>% 
  filter(income != "Not classified") %>% 
  group_by(metric, income, year) %>% 
  summarize(avg_rating = mean(value)) %>% 
  ggplot(aes(year, avg_rating)) +
  geom_line(aes(color = income)) +
  geom_line(data = overall, size = 1.5) +
  facet_wrap(~ metric) +
  expand_limits(y = 1) +
  scale_y_reverse(breaks = seq(1, 7)) +
  scale_color_discrete(guide = guide_legend(reverse = TRUE)) +
  labs(x = "Year", y = "World Freedom Index rating",
       title = "World Freedom Index rating over time by region",
       color = "Income category",
       subtitle = "Black line shows overall trend")

freedom_joined %>% 
  filter(year == 2020) %>% 
  ggplot(aes(NY.GDP.PCAP.CD, value)) +
  geom_point() +
  geom_jitter(height = .2, width = 0) +
  facet_wrap(~ metric) +
  scale_x_log10(label = comma)

```


```{r}

civil_liberties_2020 <- freedom_joined %>% 
  filter(metric == "Civil Liberties", 
         year == 2020,
         !is.na(NY.GDP.PCAP.CD))

lin_mod <- civil_liberties_2020 %>% 
  lm(value ~ region + log2(NY.GDP.PCAP.CD), data = .) 

lin_mod %>% 
  augment(civil_liberties_2020) %>% 
  select(country, NY.GDP.PCAP.CD, region, income, value, 
         .fitted, .resid) %>% 
  arrange(desc(abs(.resid))) %>% 
  head(20) %>% 
  ggplot(aes(.fitted, value)) +
  geom_point() +
  geom_abline(color = "red") +
  geom_text_repel(aes(label =  country)) +
  # scale_y_continuous(breaks =  1:7) +
  expand_limits(x = 1, y = 1) +
  labs(x = "Expected freedom index (based on region and income)", y = "Actual freedom index",
       title = "What are the largest outliers?")

```


```{r}

world <- map_data("world") %>% 
  as_tibble()

freedom_2020 <- freedom_joined %>% 
  filter(year == 2020)

world_map_freedom_2020 <- world %>%
  regex_left_join(maps::iso3166, c(region = "mapname")) %>%
  left_join(freedom_2020 %>% select(-region), by = c(a2 = "country_code")) %>% 
  filter(region != "Antarctica")

world_map_freedom_2020 %>% 
  filter(metric == "Civil Liberties") %>% 
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = value)) +
  coord_map(xlim = c(-180, 180)) +
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = 3.5,
                       guide = guide_legend(reverse = TRUE)) +
  ggthemes::theme_map() +
  labs(x = "Civil Liberties Rating", 
       title = "World Fredom Index: Civil Liberties", 
       subtitle = "In 2020")

```


```{r}

world_map_freedom <- world %>%
  regex_left_join(maps::iso3166, c(region = "mapname")) %>%
  left_join(freedom_joined %>% select(-region), by = c(a2 = "country_code")) %>% 
  filter(region != "Antarctica")

world_map_freedom %>% 
  filter(metric == "Civil Liberties") %>% 
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = value)) +
  coord_map(xlim = c(-180, 180)) +
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = 3.5,
                       guide = guide_legend(reverse = TRUE)) +
  ggthemes::theme_map() +
  transition_manual(year) +
  labs(x = "Civil Liberties Rating", 
       title = "World Fredom Index: Civil Liberties: { current_frame }")

# Static map comparing 2000 and 2020
world_map_freedom %>% 
  filter(year %in% c(2000, 2020)) %>% 
  filter(metric == "Civil Liberties") %>% 
  ggplot(aes(long, lat, group = group)) +
  geom_polygon(aes(fill = value)) +
  coord_map(xlim = c(-180, 180)) +
  scale_fill_gradient2(low = "blue", high = "red",
                       midpoint = 3.5,
                       guide = guide_legend(reverse = TRUE)) +
  ggthemes::theme_map() +
  facet_wrap(~ year, nrow = 2) +
  labs(x = "Civil Liberties Rating", 
       title = "World Fredom Index: Civil Liberties",
       subtitle = "2000 vs. 2020")

```





 























































